In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import preprocessing
from sklearn import decomposition
from sklearn import model_selection
from sklearn import linear_model
from sklearn import tree
from sklearn import neighbors
from sklearn import naive_bayes
from sklearn import ensemble
from sklearn import cluster
from sklearn import mixture
from sklearn import metrics

import matplotlib.pyplot as plt

from IPython.display import display, HTML
from typing import Callable


pd.set_option('display.max_columns', None)

In [10]:
X = np.array([
    [3, 4, 1],
    [1, 6, 2]
]).T
scaler = preprocessing.StandardScaler()
X_scaled = scaler.fit_transform(X)

np.sum(np.cov(X_scaled.T))

4.855768722395226

In [11]:
X_scaled

array([[ 0.26726124, -0.9258201 ],
       [ 1.06904497,  1.38873015],
       [-1.33630621, -0.46291005]])

In [24]:
X1 = (X[:, 0] - np.mean(X[:, 0])) / np.std(X[:, 0])
X2 = (X[:, 1] - np.mean(X[:, 1])) / np.std(X[:, 1])
X_scaled = np.array([
    X1,
    X2
]).T
X_scaled
np.cov(X_scaled.T)

array([[1.5       , 0.92788436],
       [0.92788436, 1.5       ]])

In [27]:
A = np.array([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

scaler = preprocessing.StandardScaler()
A_scaled = scaler.fit_transform(A)
A_scaled

array([[ 0.39223227,  1.86310328, -0.19425717,  1.86338998],
       [-1.89578931, -0.09805807,  1.74831455, -0.372678  ],
       [ 0.06537205, -0.58834841, -1.16554303, -0.372678  ],
       [ 1.04595272, -0.09805807, -0.6799001 , -1.11803399],
       [ 0.39223227, -1.07863874,  0.29138576,  0.        ]])

In [40]:
#определяем метод главных компонент с двумя компонентами
pca = decomposition.PCA(n_components=3)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(A_scaled)
np.sum(pca.explained_variance_ratio_)

0.955238038113975