In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import model_selection
from sklearn import linear_model
from sklearn import tree
from sklearn import ensemble
from sklearn import metrics

In [2]:
data_weather = pd.read_csv('data/weatherAUS.csv')
data_weather.head(10)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
5  2008-12-06   Albury     14.6     29.7       0.2          NaN       NaN   
6  2008-12-07   Albury     14.3     25.0       0.0          NaN       NaN   
7  2008-12-08   Albury      7.7     26.7       0.0          NaN       NaN   
8  2008-12-09   Albury      9.7     31.9       0.0          NaN       NaN   
9  2008-12-10   Albury     13.1     30.1       1.4          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   
5         WNW           56.0          W  ...        55.0         23.0   
6           W           50.0         SW  ...        49.0         19.0   
7           W           35.0        SSE  ...        48.0         19.0   
8         NNW           80.0         SE  ...        42.0          9.0   
9           W           28.0          S  ...        58.0         27.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   
5       1009.2       1005.4       NaN       NaN     20.6     28.9         No   
6       1009.6       1008.2       1.0       NaN     18.1     24.6         No   
7       1013.4       1010.1       NaN       NaN     16.3     25.5         No   
8       1008.9       1003.6       NaN       NaN     18.3     30.2         No   
9       1007.0       1005.7       NaN       NaN     20.1     28.2        Yes   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  
5            No  
6            No  
7            No  
8           Yes  
9            No  

[10 rows x 23 columns]

In [3]:
pd.set_option("display.max_columns", None)
# data_weather.drop(['Date'], axis=1).sample(10)

In [4]:
data_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Date           145460 non-null  object 
 1   Location       145460 non-null  object 
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object 
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object 
 10  WindDir3pm     141232 non-null  object 
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null

In [5]:
data_weather.isna().sum().sum()

343248

In [6]:
data_weather.isna().sum() * 100 / len(data_weather)

Date              0.000000
Location          0.000000
MinTemp           1.020899
MaxTemp           0.866905
Rainfall          2.241853
Evaporation      43.166506
Sunshine         48.009762
WindGustDir       7.098859
WindGustSpeed     7.055548
WindDir9am        7.263853
WindDir3pm        2.906641
WindSpeed9am      1.214767
WindSpeed3pm      2.105046
Humidity9am       1.824557
Humidity3pm       3.098446
Pressure9am      10.356799
Pressure3pm      10.331363
Cloud9am         38.421559
Cloud3pm         40.807095
Temp9am           1.214767
Temp3pm           2.481094
RainToday         2.241853
RainTomorrow      2.245978
dtype: float64

In [7]:
data = data_weather.drop(['Evaporation', 'Sunshine', 'Cloud3pm'], axis=1)
data.head(10)

Date Location  MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed  \
0  2008-12-01   Albury     13.4     22.9       0.6           W           44.0   
1  2008-12-02   Albury      7.4     25.1       0.0         WNW           44.0   
2  2008-12-03   Albury     12.9     25.7       0.0         WSW           46.0   
3  2008-12-04   Albury      9.2     28.0       0.0          NE           24.0   
4  2008-12-05   Albury     17.5     32.3       1.0           W           41.0   
5  2008-12-06   Albury     14.6     29.7       0.2         WNW           56.0   
6  2008-12-07   Albury     14.3     25.0       0.0           W           50.0   
7  2008-12-08   Albury      7.7     26.7       0.0           W           35.0   
8  2008-12-09   Albury      9.7     31.9       0.0         NNW           80.0   
9  2008-12-10   Albury     13.1     30.1       1.4           W           28.0   

  WindDir9am WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0          W        WNW          20.0          24.0         71.0         22.0   
1        NNW        WSW           4.0          22.0         44.0         25.0   
2          W        WSW          19.0          26.0         38.0         30.0   
3         SE          E          11.0           9.0         45.0         16.0   
4        ENE         NW           7.0          20.0         82.0         33.0   
5          W          W          19.0          24.0         55.0         23.0   
6         SW          W          20.0          24.0         49.0         19.0   
7        SSE          W           6.0          17.0         48.0         19.0   
8         SE         NW           7.0          28.0         42.0          9.0   
9          S        SSE          15.0          11.0         58.0         27.0   

   Pressure9am  Pressure3pm  Cloud9am  Temp9am  Temp3pm RainToday RainTomorrow  
0       1007.7       1007.1       8.0     16.9     21.8        No           No  
1       1010.6       1007.8       NaN     17.2     24.3        No           No  
2       1007.6       1008.7       NaN     21.0     23.2        No           No  
3       1017.6       1012.8       NaN     18.1     26.5        No           No  
4       1010.8       1006.0       7.0     17.8     29.7        No           No  
5       1009.2       1005.4       NaN     20.6     28.9        No           No  
6       1009.6       1008.2       1.0     18.1     24.6        No           No  
7       1013.4       1010.1       NaN     16.3     25.5        No           No  
8       1008.9       1003.6       NaN     18.3     30.2        No          Yes  
9       1007.0       1005.7       NaN     20.1     28.2       Yes           No

In [8]:
yes_no_binary = lambda value: value if not isinstance(value, str) else 1 if value.lower() == 'yes' else 0 if value.lower() == 'no' else value

data['RainToday'] = data['RainToday'].apply(yes_no_binary)
data['RainTomorrow'] = data['RainTomorrow'].apply(yes_no_binary)

data['Date'] = pd.to_datetime(data['Date'])
data['month'] = data['Date'].dt.month
data.drop(['Date'], axis=1, inplace=True)

display(data['RainToday'].mean())
display(data.head(10))

0.22419285648984874

Location  MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0   Albury     13.4     22.9       0.6           W           44.0          W   
1   Albury      7.4     25.1       0.0         WNW           44.0        NNW   
2   Albury     12.9     25.7       0.0         WSW           46.0          W   
3   Albury      9.2     28.0       0.0          NE           24.0         SE   
4   Albury     17.5     32.3       1.0           W           41.0        ENE   
5   Albury     14.6     29.7       0.2         WNW           56.0          W   
6   Albury     14.3     25.0       0.0           W           50.0         SW   
7   Albury      7.7     26.7       0.0           W           35.0        SSE   
8   Albury      9.7     31.9       0.0         NNW           80.0         SE   
9   Albury     13.1     30.1       1.4           W           28.0          S   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   
2        WSW          19.0          26.0         38.0         30.0   
3          E          11.0           9.0         45.0         16.0   
4         NW           7.0          20.0         82.0         33.0   
5          W          19.0          24.0         55.0         23.0   
6          W          20.0          24.0         49.0         19.0   
7          W           6.0          17.0         48.0         19.0   
8         NW           7.0          28.0         42.0          9.0   
9        SSE          15.0          11.0         58.0         27.0   

   Pressure9am  Pressure3pm  Cloud9am  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0     16.9     21.8        0.0   
1       1010.6       1007.8       NaN     17.2     24.3        0.0   
2       1007.6       1008.7       NaN     21.0     23.2        0.0   
3       1017.6       1012.8       NaN     18.1     26.5        0.0   
4       1010.8       1006.0       7.0     17.8     29.7        0.0   
5       1009.2       1005.4       NaN     20.6     28.9        0.0   
6       1009.6       1008.2       1.0     18.1     24.6        0.0   
7       1013.4       1010.1       NaN     16.3     25.5        0.0   
8       1008.9       1003.6       NaN     18.3     30.2        0.0   
9       1007.0       1005.7       NaN     20.1     28.2        1.0   

   RainTomorrow  month  
0           0.0     12  
1           0.0     12  
2           0.0     12  
3           0.0     12  
4           0.0     12  
5           0.0     12  
6           0.0     12  
7           0.0     12  
8           1.0     12  
9           0.0     12

In [9]:
data_season = data.groupby('month').mean()
data_season[['RainToday']]

RainToday
month           
1       0.189484
2       0.206746
3       0.217135
4       0.216845
5       0.222163
6       0.263638
7       0.270736
8       0.253167
9       0.229135
10      0.196512
11      0.210843
12      0.213037

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   Location       145460 non-null  object 
 1   MinTemp        143975 non-null  float64
 2   MaxTemp        144199 non-null  float64
 3   Rainfall       142199 non-null  float64
 4   WindGustDir    135134 non-null  object 
 5   WindGustSpeed  135197 non-null  float64
 6   WindDir9am     134894 non-null  object 
 7   WindDir3pm     141232 non-null  object 
 8   WindSpeed9am   143693 non-null  float64
 9   WindSpeed3pm   142398 non-null  float64
 10  Humidity9am    142806 non-null  float64
 11  Humidity3pm    140953 non-null  float64
 12  Pressure9am    130395 non-null  float64
 13  Pressure3pm    130432 non-null  float64
 14  Cloud9am       89572 non-null   float64
 15  Temp9am        143693 non-null  float64
 16  Temp3pm        141851 non-null  float64
 17  RainToday      142199 non-nul

In [11]:
categorical = ['month', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm']
dataset = pd.get_dummies(data, columns=categorical)
dataset.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'WindGustSpeed', 'WindSpeed9am',
       'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',
       'Pressure3pm',
       ...
       'WindDir3pm_NNW', 'WindDir3pm_NW', 'WindDir3pm_S', 'WindDir3pm_SE',
       'WindDir3pm_SSE', 'WindDir3pm_SSW', 'WindDir3pm_SW', 'WindDir3pm_W',
       'WindDir3pm_WNW', 'WindDir3pm_WSW'],
      dtype='object', length=124)

In [14]:
dataset.columns[dataset.columns.str.contains('month')]

Index(['month_1', 'month_2', 'month_3', 'month_4', 'month_5', 'month_6',
       'month_7', 'month_8', 'month_9', 'month_10', 'month_11', 'month_12'],
      dtype='object')

In [16]:
dataset.head()

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0     13.4     22.9       0.6           44.0          20.0          24.0   
1      7.4     25.1       0.0           44.0           4.0          22.0   
2     12.9     25.7       0.0           46.0          19.0          26.0   
3      9.2     28.0       0.0           24.0          11.0           9.0   
4     17.5     32.3       1.0           41.0           7.0          20.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Temp9am  \
0         71.0         22.0       1007.7       1007.1       8.0     16.9   
1         44.0         25.0       1010.6       1007.8       NaN     17.2   
2         38.0         30.0       1007.6       1008.7       NaN     21.0   
3         45.0         16.0       1017.6       1012.8       NaN     18.1   
4         82.0         33.0       1010.8       1006.0       7.0     17.8   

   Temp3pm  RainToday  RainTomorrow  month_1  month_2  month_3  month_4  \
0     21.8        0.0           0.0        0        0        0        0   
1     24.3        0.0           0.0        0        0        0        0   
2     23.2        0.0           0.0        0        0        0        0   
3     26.5        0.0           0.0        0        0        0        0   
4     29.7        0.0           0.0        0        0        0        0   

   month_5  month_6  month_7  month_8  month_9  month_10  month_11  month_12  \
0        0        0        0        0        0         0         0         1   
1        0        0        0        0        0         0         0         1   
2        0        0        0        0        0         0         0         1   
3        0        0        0        0        0         0         0         1   
4        0        0        0        0        0         0         0         1   

   Location_Adelaide  Location_Albany  Location_Albury  Location_AliceSprings  \
0                  0                0                1                      0   
1                  0                0                1                      0   
2                  0                0                1                      0   
3                  0                0                1                      0   
4                  0                0                1                      0   

   Location_BadgerysCreek  Location_Ballarat  Location_Bendigo  \
0                       0                  0                 0   
1                       0                  0                 0   
2                       0                  0                 0   
3                       0                  0                 0   
4                       0                  0                 0   

   Location_Brisbane  Location_Cairns  Location_Canberra  Location_Cobar  \
0                  0                0                  0               0   
1                  0                0                  0               0   
2                  0                0                  0               0   
3                  0                0                  0               0   
4                  0                0                  0               0   

   Location_CoffsHarbour  Location_Dartmoor  Location_Darwin  \
0                      0                  0                0   
1                      0                  0                0   
2                      0                  0                0   
3                      0                  0                0   
4                      0                  0                0   

   Location_GoldCoast  Location_Hobart  Location_Katherine  \
0                   0                0                   0   
1                   0                0                   0   
2                   0                0                   0   
3                   0                0                   0   
4                   0                0                   0   

   Location_Launceston  Location_Melbourne  Location_Melbo

In [26]:
dataset_ready = dataset.copy(deep=True)

dataset_ready.dropna(axis=0, inplace=True)
dataset_ready.reset_index(drop=True, inplace=True)
dataset_ready.head()

MinTemp  MaxTemp  Rainfall  WindGustSpeed  WindSpeed9am  WindSpeed3pm  \
0     13.4     22.9       0.6           44.0          20.0          24.0   
1     17.5     32.3       1.0           41.0           7.0          20.0   
2     14.3     25.0       0.0           50.0          20.0          24.0   
3     15.9     21.7       2.2           31.0          15.0          13.0   
4     15.9     18.6      15.6           61.0          28.0          28.0   

   Humidity9am  Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Temp9am  \
0         71.0         22.0       1007.7       1007.1       8.0     16.9   
1         82.0         33.0       1010.8       1006.0       7.0     17.8   
2         49.0         19.0       1009.6       1008.2       1.0     18.1   
3         89.0         91.0       1010.5       1004.2       8.0     15.9   
4         76.0         93.0        994.3        993.0       8.0     17.4   

   Temp3pm  RainToday  RainTomorrow  month_1  month_2  month_3  month_4  \
0     21.8        0.0           0.0        0        0        0        0   
1     29.7        0.0           0.0        0        0        0        0   
2     24.6        0.0           0.0        0        0        0        0   
3     17.0        1.0           1.0        0        0        0        0   
4     15.8        1.0           1.0        0        0        0        0   

   month_5  month_6  month_7  month_8  month_9  month_10  month_11  month_12  \
0        0        0        0        0        0         0         0         1   
1        0        0        0        0        0         0         0         1   
2        0        0        0        0        0         0         0         1   
3        0        0        0        0        0         0         0         1   
4        0        0        0        0        0         0         0         1   

   Location_Adelaide  Location_Albany  Location_Albury  Location_AliceSprings  \
0                  0                0                1                      0   
1                  0                0                1                      0   
2                  0                0                1                      0   
3                  0                0                1                      0   
4                  0                0                1                      0   

   Location_BadgerysCreek  Location_Ballarat  Location_Bendigo  \
0                       0                  0                 0   
1                       0                  0                 0   
2                       0                  0                 0   
3                       0                  0                 0   
4                       0                  0                 0   

   Location_Brisbane  Location_Cairns  Location_Canberra  Location_Cobar  \
0                  0                0                  0               0   
1                  0                0                  0               0   
2                  0                0                  0               0   
3                  0                0                  0               0   
4                  0                0                  0               0   

   Location_CoffsHarbour  Location_Dartmoor  Location_Darwin  \
0                      0                  0                0   
1                      0                  0                0   
2                      0                  0                0   
3                      0                  0                0   
4                      0                  0                0   

   Location_GoldCoast  Location_Hobart  Location_Katherine  \
0                   0                0                   0   
1                   0                0                   0   
2                   0                0                   0   
3                   0                0                   0   
4                   0                0                   0   

   Location_Launceston  Location_Melbourne  Location_Melbo

In [27]:
dataset_ready.shape

(78257, 124)

In [38]:
X = dataset_ready.drop(['RainTomorrow'], axis=1)
y = dataset_ready['RainTomorrow']

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.3, random_state=31)
X_train.reset_index(drop=True, inplace=True)
X_test.reset_index(drop=True, inplace=True)
y_train.reset_index(drop=True, inplace=True)
y_test.reset_index(drop=True, inplace=True)
display(np.mean(y_test))

0.22770253002811142

In [41]:
np.random.seed(31)
# np.random.randint()
train_index_min = X_train.index.min()
train_index_max = X_train.index.max()
N_train = len(X_train)
display(N_train)

bootstrap_sets = list()
mean_min_temps = list()
N_bootstraps = 1000
for ixb in range(1, N_bootstraps + 1):
    bootstrap_index = [np.random.randint(train_index_min, train_index_max) for it in range(1, N_train + 1)]
    bootstrap_set = X_train.iloc[bootstrap_index]
    # display(bootstrap_set)
    bootstrap_sets.append(bootstrap_set)
    mean_min_temps.append(bootstrap_set['MinTemp'].mean())

np.std(mean_min_temps)

54779

0.02896507245875793

In [42]:
model = linear_model.LogisticRegression(random_state=42)
model.fit(X_train, y_train)

y_test_pred = model.predict(X_test)

metrics.roc_auc_score(y_test, y_test_pred)

/home/sorcerer/.conda/envs/data-science/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7281560735675009

In [44]:
params = {
    'max_leaf_nodes': list(range(2, 10)),
    'min_samples_split': [2, 3, 4],
    'max_depth': [5,7,9,11]
}

basic_model = tree.DecisionTreeClassifier(random_state=42)
searcher = model_selection.GridSearchCV(estimator=basic_model, param_grid=params, scoring='roc_auc', cv=3, n_jobs=4)
searcher.fit(X_train, y_train)

display(searcher.best_params_)
display(searcher.best_estimator_)

y_test_pred = searcher.best_estimator_.predict(X_test)
display(metrics.roc_auc_score(y_test, y_test_pred))

{'max_depth': 5, 'max_leaf_nodes': 9, 'min_samples_split': 2}

DecisionTreeClassifier(max_depth=5, max_leaf_nodes=9, random_state=42)

0.7033229072349596

In [46]:
params = {'max_leaf_nodes': list(range(5, 15)), 'min_samples_split': [2, 3, 4], 'max_depth': [5,7,9,11]}
grid_search_cv = model_selection.GridSearchCV(tree.DecisionTreeClassifier(random_state=42), params, cv=3, n_jobs=4)
grid_search_cv.fit(X_train, y_train)
grid_search_cv.best_params_
clf = tree.DecisionTreeClassifier(max_depth = 5, max_leaf_nodes = 9, min_samples_split = 2, random_state=42)
clf.fit(X_train, y_train)
preds_train = clf.predict(X_train)
preds_test = clf.predict(X_test)
metrics.roc_auc_score(preds_test, y_test)

0.7915660105378268

In [49]:
model = ensemble.RandomForestClassifier(n_estimators=100, random_state=31, n_jobs=4)
model.fit(X_train, y_train)
y_test_pred = model.predict(X_test)
metrics.roc_auc_score(y_test, y_test_pred)

0.7329684570290497

In [52]:
params = {'max_features': [ 4, 5, 6, 7], 'min_samples_leaf': [3, 5, 7, 9, 11], 'max_depth': [5, 10, 15], 'n_estimators': [100]}
basic_model = ensemble.RandomForestClassifier(random_state=31, n_jobs=4)

searcher = model_selection.GridSearchCV(estimator=basic_model, param_grid=params, scoring='roc_auc', cv=3, n_jobs=4)
searcher.fit(X_train, y_train)

display(searcher.best_params_)
display(searcher.best_estimator_)

{'max_depth': 15,
 'max_features': 7,
 'min_samples_leaf': 3,
 'n_estimators': 100}

RandomForestClassifier(max_depth=15, max_features=7, min_samples_leaf=3,
                       n_jobs=4, random_state=31)

In [53]:
clf = ensemble.RandomForestClassifier(n_estimators=100, max_depth=15, max_features=7, min_samples_leaf=3, n_jobs=4, random_state=31)
clf.fit(X_train, y_train)
y_test_pred = searcher.best_estimator_.predict(X_test)
metrics.roc_auc_score(y_test, y_test_pred)

0.7005484843285417

In [58]:
sorted(np.column_stack((clf.feature_importances_, clf.feature_names_in_)), key=lambda it: it[0], reverse=True)

[array([0.2507825624449752, 'Humidity3pm'], dtype=object),
 array([0.07975661972737405, 'Rainfall'], dtype=object),
 array([0.07040346999571434, 'Humidity9am'], dtype=object),
 array([0.0670918140733849, 'Cloud9am'], dtype=object),
 array([0.06527182183911634, 'Pressure3pm'], dtype=object),
 array([0.06165814700498844, 'Pressure9am'], dtype=object),
 array([0.056430953695824584, 'WindGustSpeed'], dtype=object),
 array([0.047851533093357775, 'RainToday'], dtype=object),
 array([0.04316733041271845, 'Temp3pm'], dtype=object),
 array([0.03583286194424598, 'MaxTemp'], dtype=object),
 array([0.032423507986804295, 'MinTemp'], dtype=object),
 array([0.02540620347126924, 'Temp9am'], dtype=object),
 array([0.018104330876661665, 'WindSpeed3pm'], dtype=object),
 array([0.015384295746203347, 'WindSpeed9am'], dtype=object),
 array([0.005296268429782323, 'WindDir9am_N'], dtype=object),
 array([0.003106549780939253, 'WindDir9am_NNE'], dtype=object),
 array([0.0030309427193690296, 'WindDir3pm_N'], dty